### ISSUE TITLE
Error in time.py

### ISSUE THREAD

**Issue by KewTeacher** [aalfarej/Chapter-2-4#1]
When I run your program I get the following error:
`Traceback (most recent call last):
  File "/Users/davidaronson/Documents/GitHub/Chapter-2-4/time.py", line 9, in <module>
    print(alarm + "pm")
TypeError: unsupported operand type(s) for +: 'float' and 'str'`

Before you concatenate  a string you need to convert all variables to strings. Either that or use a comma instead of a plus in your print statement.
Please revise and see me if you have any questions.

**Comment by KewTeacher** [comment]
bug fixed nice work! Now it's almost there - When I enter 14 and 51 the result is:
17.0 pm
you could add `alarm % 12` after line 9 to convert to 12 hour time.

**Comment by aalfarej** [comment]
I have fixed my work please check.

**Comment by KewTeacher** [comment]
looks good
