### ISSUE TITLE
Chapter 3

### ISSUE THREAD

**Issue by KewTeacher** [aalfarej/Chapter-2-4#3]
The assignment is: "Exercises 1,3,5,6,7,8,11,12 on github - do the others for yourself - Instead of 11 or 12 you can do a creative turtle drawing with a loop in a loop"

You've done 3, 5, 7, 8,9, 11. That means you still owe me 1, 6,  8, and 12 (or a creative turtle drawing)

**Comment by aalfarej** [comment]
I finished everything please check 3.1/3.6/3.8/ and my creative drawing

**Comment by KewTeacher** [comment]
nice!
